"""added document model

Revision ID: 969549761719
Revises: d07e890d5bd2
Create Date: 2020-05-03 17:36:04.226816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '969549761719'
down_revision = 'd07e890d5bd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=140), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document')
    # ### end Alembic commands ###
