"""compnay requrirements table

Revision ID: bec718706d26
Revises: 3578a823d555
Create Date: 2021-05-28 04:47:33.019896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bec718706d26'
down_revision = '3578a823d555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cgpa', sa.Integer(), nullable=True),
    sa.Column('skills', sa.String(length=140), nullable=True),
    sa.Column('backlogs', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company')
    # ### end Alembic commands ###
