"""valid option added

Revision ID: d07e890d5bd2
Revises: b3b3d1fcb7df
Create Date: 2020-04-29 19:30:49.647464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd07e890d5bd2'
down_revision = 'b3b3d1fcb7df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('valid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'valid')
    # ### end Alembic commands ###
